### PR TITLE
Adding Prometheus JMX Exporter to Collect metrics on Hawkular Services

### PR DESCRIPTION
**Pull request by gbaufake**
- Using Prometheus JMX Exporter (https://github.com/prometheus/jmx_exporter) to collect hawkular services' metrics on prometheus.

- Metrics to be collected 
       - jvm_memory_bytes_used{area="heap",}
       - jvm_memory_bytes_used{area="nonheap",}
       - jvm_memory_bytes_committed{area="heap",}
       - jvm_memory_bytes_committed{area="nonheap",}
       - jvm_memory_pool_bytes_committed{pool="Code Cache",}
       - jvm_memory_bytes_max{area="heap",}
       - jvm_memory_bytes_max{area="nonheap",}
       - jvm_memory_pool_bytes_used{pool="Code Cache",}
       - jvm_memory_pool_bytes_used{pool="Metaspace",}
       - jvm_memory_pool_bytes_used{pool="Compressed Class Space",}
       - jvm_memory_pool_bytes_used{pool="PS Eden Space",}
       - jvm_memory_pool_bytes_used{pool="PS Survivor Space",}
       - jvm_memory_pool_bytes_used{pool="PS Old Gen",}
       - jvm_memory_pool_bytes_committed{pool="Code Cache",}
       - jvm_memory_pool_bytes_committed{pool="Metaspace",}
       - jvm_memory_pool_bytes_committed{pool="Compressed Class Space",}
       - jvm_memory_pool_bytes_committed{pool="PS Eden Space",}
       - jvm_memory_pool_bytes_committed{pool="PS Survivor Space",}
       - jvm_memory_pool_bytes_committed{pool="PS Old Gen",}
       - jvm_memory_pool_bytes_max{pool="Code Cache",}
       - jvm_memory_pool_bytes_max{pool="Compressed Class Space",}
       - jvm_memory_pool_bytes_max{pool="PS Eden Space",}
       - jvm_memory_pool_bytes_max{pool="PS Survivor Space",}
       - jvm_memory_pool_bytes_max{pool="PS Old Gen",}

The Hawkular Services + Prometheus JMX image was submmited to https://hub.docker.com/r/gbaufake/hawkular-services-jmx/

### CODE REVIEW

**Comment by lucasponce** [comment]
Note that the jmx-exporter would work only for inventory only.
When we test the hawkular-services, if the agent is embedded, then it would add a jmx-exporter too, so this config then should change.

**Comment by lucasponce** [comment]
I see, it is using latest, I am not sure if the agent is deployed.
I know there is a developer configuration using the -Pdev profile which is the way I test locally the environment, but I don't know if the docker image has also the agent in place.
@jmazzitelli worked in the docker image, mazz, do you remember if the hawkular-services docker image includes the agent ?

**Comment by gbaufake** [comment]
@lucasponce I think the latest services includes the agent
Some lines which were extracted from hawkular-services-jmx-exporter docker image:

> 18:52:12,836 INFO  [org.hawkular.cmdgw.command.ws.server.FeedWebSocket] (default task-10) HAWKFEEDCOMM000013: WebSocket session [hawkular-services-2-cjj42] opened for endpoint [/feed/{feedId}]
18:52:12,947 INFO [org.xnio] (Hawkular Java Agent Start Thread) XNIO version 3.3.4.Final
18:52:12,983 INFO [org.xnio.nio] (Hawkular Java Agent Start Thread) XNIO NIO Implementation Version 3.3.4.Final
18:52:13,680 INFO [org.hawkular.agent.monitor.protocol.ProtocolServices] (Hawkular Java Agent Start Thread) HAWKAGENT010057: Auto-discovery scans will be performed every [600] seconds

**Comment by lucasponce** [comment]
Then you should use just that, if not you are installing two on the same server, and perhaps that might create some conflicts.
Anyway, lets @jmazzitelli take a look as he is more familiar with it.

**Comment by jmazzitelli** [comment]
Yes, the docker image contains the agent that is enabled (it took a while to find out where the enabled flag is actually getting set to true :) but it is here: https://github.com/hawkular/hawkular-services/blob/hawkular-1275/docker-dist/pom.xml#L43 )

You should not be installing your own version of jmx exporter. The agent will download the proper jmx exporter config from the h-server and start a jmx exporter endpoint for you. The h-agent's jmx exporter's config will be compatible with the inventory that the agent stores. This means the inventory metric metadata will correspond to the JMX exporter data being collected and thus you can get the data from Prometheus by looking up metric family/labels from inventory. (note: shortly you will have available a metric-expression in inventory that you can use to directly query Prometheus with - that will go in the next services docker image released).

If you have your own JMX exporter agent, that will simply be external to anything Hawkular-related.

Note that this is true only of the hawkular-1275 branch and related binaries. See the hawkular-1275 tag in docker hub: https://hub.docker.com/r/hawkular/hawkular-services/tags/

This isn't in master yet (we _really_ need to get 1275 merged into master, it is taking too long).

**Comment by gbaufake** [comment]
@lucasponce, @jmazzitelli 
Considering today meeting, is it okay to merge it?

**Pull request closed without merging**
